include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)/arch/arm/mach-$(MTK_PLATFORM)/$(ARCH_MTK_PROJECT)/touchpanel/msg2133/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/msg2133/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

obj-y := msg2133_driver.o

